-- =============================================================================
-- insight-api schema (database: insight_db)
--
-- JPA 엔티티에서 손으로 도출한 DDL. 권위 있는 원본은 Hibernate 생성 DDL.
-- 타입 규칙: IDENTITY -> BIGINT GENERATED BY DEFAULT AS IDENTITY,
--            Instant -> timestamptz(6), LocalDate -> date, Enum -> varchar(길이).
-- =============================================================================

-- 활동 이벤트 (원장) ----------------------------------------------------------
CREATE TABLE insight_activity_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    type            VARCHAR(32)  NOT NULL,
    occurred_at     TIMESTAMPTZ  NOT NULL,
    score           INTEGER      NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    meta_json       JSONB,
    created_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_activity_event_idem UNIQUE (idempotency_key)
);
CREATE INDEX ix_activity_event_user_time ON insight_activity_event (user_id, occurred_at);

-- 일별 집계 (잔디, 복합 PK) ---------------------------------------------------
CREATE TABLE insight_activity_daily (
    user_id        BIGINT      NOT NULL,
    activity_date  DATE        NOT NULL,
    event_count    INTEGER     NOT NULL,
    score_sum      INTEGER     NOT NULL,
    breakdown_json JSONB       NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, activity_date)
);
CREATE INDEX ix_activity_daily_user_date ON insight_activity_daily (user_id, activity_date DESC);

-- DLQ (Kafka 처리 실패 격리) --------------------------------------------------
CREATE TABLE insight_activity_event_dlq (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_payload     TEXT         NOT NULL,
    idempotency_key VARCHAR(128),
    failure_kind    VARCHAR(16)  NOT NULL,
    last_error      TEXT         NOT NULL,
    status          VARCHAR(12)  NOT NULL,
    attempts        INTEGER      NOT NULL,
    failed_at       TIMESTAMPTZ  NOT NULL,
    next_retry_at   TIMESTAMPTZ  NOT NULL,
    resolved_at     TIMESTAMPTZ
);
CREATE INDEX ix_activity_dlq_status    ON insight_activity_event_dlq (status, next_retry_at);
CREATE INDEX ix_activity_dlq_failed_at ON insight_activity_event_dlq (failed_at);

-- shedlock --------------------------------------------------------------------
CREATE TABLE shedlock (
    name       VARCHAR(64)  PRIMARY KEY,
    lock_until TIMESTAMPTZ  NOT NULL,
    locked_at  TIMESTAMPTZ  NOT NULL,
    locked_by  VARCHAR(255) NOT NULL
);
