-- =============================================================================
-- iam-api schema (database: iam_db)
--
-- JPA 엔티티에서 손으로 도출한 DDL. 권위 있는 원본은 Hibernate 가 생성하는 DDL이며,
-- 정확한 대조가 필요하면 ddl-auto=create 로 scratch DB 에 생성 후 pg_dump 로 비교할 것.
--
-- 타입 규칙:
--   Long @Id @GeneratedValue(IDENTITY) -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   Instant                            -> timestamptz(6)   (Hibernate 6: TIMESTAMP_UTC)
--   LocalDateTime                      -> timestamp(6)
--   LocalDate                          -> date
--   Enum(EnumType.STRING)              -> varchar(길이)
--   jsonb                              -> jsonb
-- FK: 엔티티가 연관을 raw Long id 로만 매핑 -> Hibernate 가 FK 를 만들지 않음.
--     따라서 여기서도 서비스 간/내 FK 를 두지 않음(운영에서 필요 시 별도 추가).
-- =============================================================================

-- users -----------------------------------------------------------------------
CREATE TABLE iam_user (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(254),
    handle               VARCHAR(39)  NOT NULL,
    display_name         VARCHAR(100) NOT NULL,
    avatar_url           VARCHAR(1024),
    bio                  VARCHAR(280),
    status               VARCHAR(24)  NOT NULL,
    pending_deletion_at  TIMESTAMPTZ,
    language             VARCHAR(16),
    timezone             VARCHAR(64),
    theme                VARCHAR(16)  NOT NULL,
    default_workspace_id BIGINT,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL
);
CREATE UNIQUE INDEX ux_iam_user_handle ON iam_user (handle);
CREATE INDEX        ix_iam_user_email  ON iam_user (email);

-- social identities -----------------------------------------------------------
CREATE TABLE iam_social_identity (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    provider         VARCHAR(32)  NOT NULL,
    provider_user_id VARCHAR(128) NOT NULL,
    provider_email   VARCHAR(254),
    profile_url      VARCHAR(512),
    linked_at        TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_iam_social_identity_provider_user UNIQUE (provider, provider_user_id)
);
CREATE INDEX ix_iam_social_identity_user ON iam_social_identity (user_id);

-- refresh tokens --------------------------------------------------------------
CREATE TABLE iam_refresh_token (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    family_id        UUID         NOT NULL,
    token_hash       VARCHAR(128) NOT NULL,
    remember_me      BOOLEAN      NOT NULL,
    expires_at       TIMESTAMPTZ  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    revoked_at       TIMESTAMPTZ,
    replaced_by_hash VARCHAR(128),
    device_label     VARCHAR(120),
    user_agent       VARCHAR(512),
    ip_address       VARCHAR(64),
    last_used_at     TIMESTAMPTZ,
    CONSTRAINT uq_iam_refresh_token_hash UNIQUE (token_hash)
);
CREATE INDEX ix_iam_refresh_token_user   ON iam_refresh_token (user_id);
CREATE INDEX ix_iam_refresh_token_family ON iam_refresh_token (family_id);

-- workspaces ------------------------------------------------------------------
CREATE TABLE iam_workspace (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(50) NOT NULL,
    slug                 VARCHAR(40) NOT NULL,
    notification_enabled BOOLEAN     NOT NULL,
    default_timezone     VARCHAR(64) NOT NULL,
    created_by_user_id   BIGINT      NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_iam_workspace_slug UNIQUE (slug)
);
CREATE INDEX ix_iam_workspace_creator ON iam_workspace (created_by_user_id);

-- workspace members -----------------------------------------------------------
CREATE TABLE iam_workspace_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT      NOT NULL,
    user_id      BIGINT      NOT NULL,
    role         VARCHAR(16) NOT NULL,
    joined_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_iam_workspace_member_ws_user UNIQUE (workspace_id, user_id)
);
CREATE INDEX ix_iam_workspace_member_user      ON iam_workspace_member (user_id);
CREATE INDEX ix_iam_workspace_member_workspace ON iam_workspace_member (workspace_id);

-- workspace invitations -------------------------------------------------------
CREATE TABLE iam_workspace_invitation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id        BIGINT       NOT NULL,
    invited_by_user_id  BIGINT       NOT NULL,
    type                VARCHAR(16)  NOT NULL,
    email               VARCHAR(254),
    token_hash          VARCHAR(128) NOT NULL,
    role                VARCHAR(16)  NOT NULL,
    status              VARCHAR(16)  NOT NULL,
    expires_at          TIMESTAMPTZ  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL,
    accepted_at         TIMESTAMPTZ,
    accepted_by_user_id BIGINT,
    CONSTRAINT uq_iam_workspace_invitation_token UNIQUE (token_hash)
);
CREATE INDEX ix_iam_workspace_invitation_workspace ON iam_workspace_invitation (workspace_id);
CREATE INDEX ix_iam_workspace_invitation_status    ON iam_workspace_invitation (status);

-- follows ---------------------------------------------------------------------
CREATE TABLE iam_follow (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT      NOT NULL,
    followee_id BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_iam_follow_follower_followee UNIQUE (follower_id, followee_id)
);
CREATE INDEX ix_iam_follow_followee ON iam_follow (followee_id);
CREATE INDEX ix_iam_follow_follower ON iam_follow (follower_id);

-- outbox ----------------------------------------------------------------------
CREATE TABLE iam_outbox_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(40)  NOT NULL,
    aggregate_id   VARCHAR(80)  NOT NULL,
    topic          VARCHAR(120) NOT NULL,
    kafka_key      VARCHAR(120),
    payload        JSONB        NOT NULL,
    status         VARCHAR(12)  NOT NULL,
    attempts       INTEGER      NOT NULL,
    last_error     TEXT,
    created_at     TIMESTAMPTZ  NOT NULL,
    sent_at        TIMESTAMPTZ,
    next_retry_at  TIMESTAMPTZ  NOT NULL
);
CREATE INDEX ix_iam_outbox_pending        ON iam_outbox_event (status, next_retry_at);
CREATE INDEX ix_iam_outbox_sent_for_purge ON iam_outbox_event (sent_at);

-- shedlock (분산 스케줄러 락) --------------------------------------------------
CREATE TABLE shedlock (
    name       VARCHAR(64)  PRIMARY KEY,
    lock_until TIMESTAMPTZ  NOT NULL,
    locked_at  TIMESTAMPTZ  NOT NULL,
    locked_by  VARCHAR(255) NOT NULL
);
