-- =============================================================================
-- core-api schema (database: core_db)
--
-- JPA 엔티티에서 손으로 도출한 DDL. 권위 있는 원본은 Hibernate 생성 DDL.
--
-- 타입 규칙:
--   Long @Id @GeneratedValue(IDENTITY) -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   Instant                            -> timestamptz(6)
--   LocalDateTime                      -> timestamp(6)
--   Enum(EnumType.STRING)              -> varchar(길이)
--   TEXT columnDefinition              -> text
-- 주의: 이 서비스는 case/comment/step/solution 이 LocalDateTime,
--       attachment/snippet/outbox 가 Instant 를 쓴다 (컬럼 타입이 섞임).
-- FK: raw Long id 매핑이라 대부분 FK 없음. 단 solution 의 @ElementCollection 은
--     error_case_solution_step -> error_case_solution FK 를 Hibernate 가 생성.
-- =============================================================================

-- error_case ------------------------------------------------------------------
CREATE TABLE error_case (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                      VARCHAR(200) NOT NULL,
    project                    VARCHAR(200),
    description                TEXT,
    -- ErrorSnapshotEmbeddable
    snapshot_raw_paste         TEXT,
    snapshot_exception_class   VARCHAR(500),
    snapshot_exception_message TEXT,
    snapshot_raw_stacktrace    TEXT,
    snapshot_fingerprint       VARCHAR(128),
    -- MetaEmbeddable
    meta_workspace_id          BIGINT,
    meta_severity              INTEGER,
    -- status/visibility
    status                     VARCHAR(20) NOT NULL,
    visibility                 VARCHAR(16) NOT NULL,
    occurred_at                TIMESTAMP(6),
    created_at                 TIMESTAMP(6) NOT NULL,
    updated_at                 TIMESTAMP(6) NOT NULL,
    owner_user_id              BIGINT NOT NULL,
    resolved_at                TIMESTAMP(6),
    resolved_by_user_id        BIGINT
);
CREATE INDEX ix_error_case_workspace   ON error_case (meta_workspace_id);
CREATE INDEX ix_error_case_fingerprint ON error_case (snapshot_fingerprint);
CREATE INDEX ix_error_case_created_at  ON error_case (created_at);
CREATE INDEX ix_error_case_visibility  ON error_case (visibility);

-- error_case_tag --------------------------------------------------------------
CREATE TABLE error_case_tag (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_case_id BIGINT      NOT NULL,
    tag           VARCHAR(32) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_error_case_tag UNIQUE (error_case_id, tag)
);
CREATE INDEX ix_error_case_tag_tag ON error_case_tag (tag);

-- error_case_me_too -----------------------------------------------------------
CREATE TABLE error_case_me_too (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_case_id BIGINT       NOT NULL,
    user_id       BIGINT       NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_case_me_too_user UNIQUE (error_case_id, user_id)
);
CREATE INDEX ix_case_me_too_case ON error_case_me_too (error_case_id);

-- case_view (복합 PK) ---------------------------------------------------------
CREATE TABLE case_view (
    user_id        BIGINT       NOT NULL,
    error_case_id  BIGINT       NOT NULL,
    last_viewed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (user_id, error_case_id)
);
CREATE INDEX ix_case_view_case ON case_view (error_case_id);

-- error_case_watchlist --------------------------------------------------------
CREATE TABLE error_case_watchlist (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_case_id BIGINT       NOT NULL,
    user_id       BIGINT       NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_case_watchlist_user UNIQUE (error_case_id, user_id)
);
CREATE INDEX ix_case_watchlist_case ON error_case_watchlist (error_case_id);
CREATE INDEX ix_case_watchlist_user ON error_case_watchlist (user_id);

-- error_case_comment ----------------------------------------------------------
CREATE TABLE error_case_comment (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_case_id            BIGINT       NOT NULL,
    author_user_id           BIGINT       NOT NULL,
    parent_comment_id        BIGINT,
    body                     TEXT         NOT NULL,
    quote_source_kind        VARCHAR(16)  NOT NULL,
    quote_source_id          BIGINT,
    quote_snapshot           VARCHAR(500),
    quote_snapshot_truncated BOOLEAN      NOT NULL,
    edited_at                TIMESTAMP(6),
    deleted_at               TIMESTAMP(6),
    created_at               TIMESTAMP(6) NOT NULL,
    updated_at               TIMESTAMP(6) NOT NULL
);
CREATE INDEX ix_comment_case_created ON error_case_comment (error_case_id, created_at);
CREATE INDEX ix_comment_parent       ON error_case_comment (parent_comment_id);
CREATE INDEX ix_comment_author       ON error_case_comment (author_user_id);

-- error_case_comment_mention --------------------------------------------------
CREATE TABLE error_case_comment_mention (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id           BIGINT       NOT NULL,
    mentioned_identifier VARCHAR(100) NOT NULL,
    mentioned_user_id    BIGINT
);
CREATE INDEX ix_comment_mention_comment ON error_case_comment_mention (comment_id);
CREATE INDEX ix_comment_mention_user    ON error_case_comment_mention (mentioned_user_id);

-- error_case_comment_reaction -------------------------------------------------
CREATE TABLE error_case_comment_reaction (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    emoji      VARCHAR(16)  NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_comment_reaction_user_emoji UNIQUE (comment_id, user_id, emoji)
);
CREATE INDEX ix_comment_reaction_comment ON error_case_comment_reaction (comment_id);

-- error_case_comment_helpful --------------------------------------------------
CREATE TABLE error_case_comment_helpful (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_comment_helpful_user UNIQUE (comment_id, user_id)
);
CREATE INDEX ix_comment_helpful_comment ON error_case_comment_helpful (comment_id);

-- error_case_comment_suggestion -----------------------------------------------
CREATE TABLE error_case_comment_suggestion (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id  BIGINT       NOT NULL,
    source_type VARCHAR(32)  NOT NULL,
    source_id   VARCHAR(128) NOT NULL,
    start_line  INTEGER      NOT NULL,
    end_line    INTEGER      NOT NULL,
    old_code    TEXT         NOT NULL,
    new_code    TEXT         NOT NULL,
    status      VARCHAR(16)  NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_comment_suggestion_comment UNIQUE (comment_id)
);
CREATE INDEX ix_comment_suggestion_source ON error_case_comment_suggestion (source_type, source_id);
CREATE INDEX ix_comment_suggestion_status ON error_case_comment_suggestion (status);

-- error_case_attachment (Instant) ---------------------------------------------
CREATE TABLE error_case_attachment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_case_id       BIGINT,
    marker_id           VARCHAR(32)  NOT NULL,
    title               VARCHAR(200),
    caption             TEXT,
    file_name           VARCHAR(500) NOT NULL,
    content_type        VARCHAR(200) NOT NULL,
    size                BIGINT       NOT NULL,
    kind                VARCHAR(20)  NOT NULL,
    object_key          VARCHAR(512) NOT NULL,
    uploaded_by_user_id BIGINT       NOT NULL,
    uploaded_at         TIMESTAMPTZ  NOT NULL
);
CREATE UNIQUE INDEX ix_attachment_marker          ON error_case_attachment (marker_id);
CREATE INDEX        ix_attachment_error_case      ON error_case_attachment (error_case_id);
CREATE INDEX        ix_attachment_uploader_orphan ON error_case_attachment (uploaded_by_user_id, error_case_id);
CREATE INDEX        ix_attachment_orphan_gc       ON error_case_attachment (error_case_id, uploaded_at);

-- error_case_snippet (Instant) ------------------------------------------------
CREATE TABLE error_case_snippet (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_case_id       BIGINT,
    marker_id           VARCHAR(32)  NOT NULL,
    title               VARCHAR(200) NOT NULL,
    language            VARCHAR(30)  NOT NULL,
    file_path_or_class  VARCHAR(500),
    line_range          VARCHAR(50),
    caption             TEXT,
    code                TEXT         NOT NULL,
    uploaded_by_user_id BIGINT       NOT NULL,
    uploaded_at         TIMESTAMPTZ  NOT NULL
);
CREATE UNIQUE INDEX ix_snippet_marker     ON error_case_snippet (marker_id);
CREATE INDEX        ix_snippet_error_case ON error_case_snippet (error_case_id);
CREATE INDEX        ix_snippet_orphan_gc  ON error_case_snippet (error_case_id, uploaded_at);

-- error_case_step -------------------------------------------------------------
CREATE TABLE error_case_step (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_case_id  BIGINT       NOT NULL,
    author_user_id BIGINT       NOT NULL,
    order_index    INTEGER      NOT NULL,
    title          VARCHAR(200) NOT NULL,
    status         VARCHAR(16)  NOT NULL,
    attempt_type   VARCHAR(64),
    body           TEXT,
    insight        VARCHAR(500),
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL
);
CREATE INDEX ix_step_case_order ON error_case_step (error_case_id, order_index);
CREATE INDEX ix_step_author     ON error_case_step (author_user_id);

-- step_attempt_type_custom ----------------------------------------------------
CREATE TABLE step_attempt_type_custom (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    name       VARCHAR(64)  NOT NULL,
    normalized VARCHAR(64)  NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_step_attempt_type_custom UNIQUE (user_id, normalized)
);
CREATE INDEX ix_step_attempt_type_custom_user ON step_attempt_type_custom (user_id);

-- error_case_solution + step link (element collection) ------------------------
CREATE TABLE error_case_solution (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_case_id  BIGINT       NOT NULL,
    author_user_id BIGINT       NOT NULL,
    title          VARCHAR(200) NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL
);
CREATE INDEX ix_solution_case   ON error_case_solution (error_case_id);
CREATE INDEX ix_solution_author ON error_case_solution (author_user_id);

CREATE TABLE error_case_solution_step (
    solution_id BIGINT  NOT NULL,
    step_id     BIGINT  NOT NULL,
    order_index INTEGER NOT NULL,
    PRIMARY KEY (solution_id, order_index),
    CONSTRAINT fk_solution_step_solution FOREIGN KEY (solution_id) REFERENCES error_case_solution (id)
);
CREATE INDEX ix_solution_step_step ON error_case_solution_step (step_id);

-- outbox (Instant) ------------------------------------------------------------
CREATE TABLE core_outbox_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(40)  NOT NULL,
    aggregate_id   VARCHAR(80)  NOT NULL,
    topic          VARCHAR(120) NOT NULL,
    kafka_key      VARCHAR(120),
    payload        JSONB        NOT NULL,
    status         VARCHAR(12)  NOT NULL,
    attempts       INTEGER      NOT NULL,
    last_error     TEXT,
    created_at     TIMESTAMPTZ  NOT NULL,
    sent_at        TIMESTAMPTZ,
    next_retry_at  TIMESTAMPTZ  NOT NULL
);
CREATE INDEX ix_core_outbox_pending        ON core_outbox_event (status, next_retry_at);
CREATE INDEX ix_core_outbox_sent_for_purge ON core_outbox_event (sent_at);

-- shedlock --------------------------------------------------------------------
CREATE TABLE shedlock (
    name       VARCHAR(64)  PRIMARY KEY,
    lock_until TIMESTAMPTZ  NOT NULL,
    locked_at  TIMESTAMPTZ  NOT NULL,
    locked_by  VARCHAR(255) NOT NULL
);
