-- =============================================================================
-- 케이스 생성 멱등성 기록 (POST /error-cases)
--
-- 같은 (idempotency_key, user_id) 재요청은 최초 error_case id 로 재생 → 더블클릭/
-- 네트워크 재시도로 인한 중복 케이스 생성을 서버에서 차단.
-- created_at 은 CaseIdempotencyCleanupJob(48h) 정리 기준. Instant -> timestamptz(6).
-- =============================================================================

CREATE TABLE case_idempotency (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(200) NOT NULL,
    user_id         BIGINT NOT NULL,
    request_hash    VARCHAR(64) NOT NULL,
    error_case_id   BIGINT NOT NULL,
    created_at      TIMESTAMPTZ(6) NOT NULL,
    CONSTRAINT uq_case_idem_key_user UNIQUE (idempotency_key, user_id)
);
CREATE INDEX ix_case_idem_created ON case_idempotency (created_at);
