-- =============================================================================
-- noti-api schema (database: noti_db)
--
-- JPA 엔티티에서 손으로 도출한 DDL. 권위 있는 원본은 Hibernate 생성 DDL.
-- 타입 규칙: IDENTITY -> BIGINT GENERATED BY DEFAULT AS IDENTITY,
--            Instant -> timestamptz(6), Enum -> varchar(길이), jsonb -> jsonb.
-- =============================================================================

-- 알림 (inbox) ----------------------------------------------------------------
CREATE TABLE noti_notification (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT      NOT NULL,
    type              VARCHAR(40) NOT NULL,
    actor_user_id     BIGINT,
    payload           JSONB       NOT NULL,
    read_at           TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL
);
-- inbox 조회: WHERE recipient_user_id = ? ORDER BY created_at DESC
CREATE INDEX ix_noti_recipient_created ON noti_notification (recipient_user_id, created_at DESC);

-- 사용자 알림 설정 (PK = user_id) ---------------------------------------------
CREATE TABLE noti_user_notification_settings (
    user_id    BIGINT      PRIMARY KEY,
    settings   JSONB       NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

-- 디바이스 토큰 (푸시) --------------------------------------------------------
CREATE TABLE noti_device_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token      VARCHAR(512) NOT NULL,
    platform   VARCHAR(16)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_noti_device_token UNIQUE (user_id, token)
);
CREATE INDEX ix_noti_device_token_user ON noti_device_token (user_id);
