-- =============================================================================
-- noti-api V2 — Kafka consumer 실패 이벤트 DLQ (자동 재처리)
-- NotificationEventDlqEntity 와 1:1. 타입 규칙: IDENTITY -> BIGINT GENERATED BY DEFAULT AS IDENTITY,
--   Instant -> TIMESTAMPTZ, Enum -> varchar(길이).
-- =============================================================================

CREATE TABLE noti_notification_event_dlq (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type    VARCHAR(32) NOT NULL,   -- KafkaEventType (MENTION / REPLY / ...)
    raw_payload   TEXT        NOT NULL,    -- 원본 Kafka JSON
    failure_kind  VARCHAR(16) NOT NULL,    -- PARSE / INGEST
    last_error    TEXT        NOT NULL,
    status        VARCHAR(12) NOT NULL,    -- PENDING / RESOLVED / DEAD
    attempts      INTEGER     NOT NULL DEFAULT 0,
    failed_at     TIMESTAMPTZ NOT NULL,
    next_retry_at TIMESTAMPTZ NOT NULL,
    resolved_at   TIMESTAMPTZ
);

-- retry 잡 polling: WHERE status='PENDING' AND failure_kind='INGEST' AND next_retry_at <= now
CREATE INDEX ix_noti_dlq_status ON noti_notification_event_dlq (status, next_retry_at);
CREATE INDEX ix_noti_dlq_failed_at ON noti_notification_event_dlq (failed_at);
