-- =============================================================================
-- publish-api schema (database: publish_db)
--
-- JPA 엔티티에서 손으로 도출한 DDL. 권위 있는 원본은 Hibernate 생성 DDL.
-- 타입 규칙: IDENTITY -> BIGINT GENERATED BY DEFAULT AS IDENTITY,
--            LocalDateTime -> timestamp(6), Instant -> timestamptz(6),
--            Enum -> varchar(길이), jsonb -> jsonb.
-- =============================================================================

-- 발행물 (케이스당 1 canonical) -----------------------------------------------
CREATE TABLE case_publishment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(32)  NOT NULL,
    owner_user_id   BIGINT       NOT NULL,
    original_case_id BIGINT      NOT NULL,
    title           VARCHAR(200) NOT NULL,
    summary         VARCHAR(500),
    visibility      VARCHAR(16)  NOT NULL,
    content_json    JSONB        NOT NULL,
    options_json    JSONB        NOT NULL,
    version         INTEGER      NOT NULL,
    view_count      BIGINT       NOT NULL,
    download_count  BIGINT       NOT NULL,
    published_at    TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    source_state    VARCHAR(16)  NOT NULL,
    status          VARCHAR(16)  NOT NULL,
    CONSTRAINT uq_case_publishment_slug   UNIQUE (slug),
    CONSTRAINT uq_case_publishment_origin UNIQUE (original_case_id)
);
CREATE INDEX ix_case_publishment_owner                ON case_publishment (owner_user_id);
CREATE INDEX ix_case_publishment_visibility_published ON case_publishment (visibility, published_at DESC);

-- 발행 멱등성 기록 ------------------------------------------------------------
CREATE TABLE publish_idempotency (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key  VARCHAR(200) NOT NULL,
    user_id          BIGINT       NOT NULL,
    request_hash     VARCHAR(64)  NOT NULL,
    publishment_slug VARCHAR(32)  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_publish_idem_key_user UNIQUE (idempotency_key, user_id)
);
CREATE INDEX ix_publish_idem_created ON publish_idempotency (created_at);

-- outbox (Instant) ------------------------------------------------------------
CREATE TABLE pub_outbox_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(40)  NOT NULL,
    aggregate_id   VARCHAR(80)  NOT NULL,
    topic          VARCHAR(120) NOT NULL,
    kafka_key      VARCHAR(120),
    payload        JSONB        NOT NULL,
    status         VARCHAR(12)  NOT NULL,
    attempts       INTEGER      NOT NULL,
    last_error     TEXT,
    created_at     TIMESTAMPTZ  NOT NULL,
    sent_at        TIMESTAMPTZ,
    next_retry_at  TIMESTAMPTZ  NOT NULL
);
CREATE INDEX ix_pub_outbox_pending        ON pub_outbox_event (status, next_retry_at);
CREATE INDEX ix_pub_outbox_sent_for_purge ON pub_outbox_event (sent_at);

-- shedlock --------------------------------------------------------------------
CREATE TABLE shedlock (
    name       VARCHAR(64)  PRIMARY KEY,
    lock_until TIMESTAMPTZ  NOT NULL,
    locked_at  TIMESTAMPTZ  NOT NULL,
    locked_by  VARCHAR(255) NOT NULL
);
