apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# stg 환경(=alpha 브랜치). 네임스페이스 apps.
# 주의: 현재 배포는 prod 스프링 프로파일 + .env.prod 로 동작 → 여기 SPRING_PROFILES_ACTIVE=prod 유지.
namespace: apps

resources:
- ../../base/iam-api
- ../../base/core-api
- ../../base/noti-api
- ../../base/insight-api

configMapGenerator:
- literals:
  - SPRING_PROFILES_ACTIVE=prod
  name: iam-api-env
- literals:
  - SPRING_PROFILES_ACTIVE=prod
  name: core-api-env
- literals:
  - SPRING_PROFILES_ACTIVE=prod
  name: noti-api-env
- literals:
  - SPRING_PROFILES_ACTIVE=prod
  name: insight-api-env
generatorOptions:
  disableNameSuffixHash: true

# GitHub Actions(bump-manifest)가 newTag 를 커밋 SHA 로 갱신. 초기값 stg.
images:
- name: core-api
  newName: ghcr.io/studieo-javry/core-api
  newTag: 8f1f777d66aa1de417b138d5f5ecfccc94d5be04
- name: iam-api
  newName: ghcr.io/studieo-javry/iam-api
  newTag: 8f1f777d66aa1de417b138d5f5ecfccc94d5be04
- name: insight-api
  newName: ghcr.io/studieo-javry/insight-api
  newTag: 84efa4f8b2b3ba6c71ad839eebab1d1b63a29c75
- name: noti-api
  newName: ghcr.io/studieo-javry/noti-api
  newTag: 4a39a77ce3361e1585551ba2a4456656124aa8cc
